config/routes.rb
Rails.application.routes.draw do
    root to: 'visitors#index'


    # user routes
    resources  :users do
      resources :campaigns
    end

    get 'users/:id/user_posts' => 'users#user_posts', :as => :custom_user_posts
    # string -- user.email.split("@")[0]


    # session routes
    get '/login' => 'users#login'
    get '/auth/:provider/callback' => 'sessions#create'
    get '/signin' => 'sessions#new', :as => :signin
    get '/signout' => 'sessions#destroy', :as => :signout
    get '/auth/failure' => 'sessions#failure'

    # campaign routes
    get '/c/index' => 'campaigns#index', as: :index_campaign
    get '/c/create' => 'campaigns#campaign_creation', as: :create_campaign
    post '/c/create' => 'campaigns#show'
    get '/c/:id' => 'campaigns#show', as: :show_campaign
    resources :campaigns do
      resources :comments
    end

    resources :comments do
      resources :comments
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end

    resources :comments do 
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end

  end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  belongs_to :campaign
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  
end

app/controllers/comments_controller.rb
  class CommentsController < ApplicationController
  before_action :authenticate_user!, :only => [:create]
  before_action :find_commentable

  def new
    @comment = Comment.new
  end

  def create
    @comment = @commentable.comments.new comment_params
    @comment.user = current_user

    if @comment.save
      redirect_to :back, notice: 'Your comment was successfully posted!'
    else
      redirect_to :back, notice: "Your comment wasn't posted!"
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
    if @comment.update_attributes(comment_params)
      format.html { redirect_to(comment_params[:campaign_id, :action => 'show' , :notice => 'Comment was successfully updated.']) }
      format.json { respond_with_bip(comment_params) }
    else
      format.html { render :action => "edit" }
      format.json { respond_with_bip(@comment) }
    end
    end 
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    if @comment.destroy
      redirect_to :back, notice: "Comment deleted."
    end
  end

  def upvote 
    @comment = Comment.find(params[:id])
    @comment.upvote_by current_user
    redirect_to :back
  end  

  def downvote
    @comment = Comment.find(params[:id])
    @comment.downvote_by current_user
    redirect_to :back
  end

  private

  def comment_params
    params.require(:comment).permit(:campaign_id, :body, :user_id)
  end

  def find_commentable
    @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    @commentable = Campaign.find_by_id(params[:campaign_id]) if params[:campaign_id]
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<small><b><%= link_to comment.user.name, comment.user %></b> <i>said <%= time_ago_in_words(comment.created_at) %> ago:</i></small>
<br>
<%= markdown(comment.body) %>
<div class="accordion">
  <div class="panel">
    <small>
      <%= link_to like_comment_path(comment), method: :put do %>
        &#x25B2
      <%= comment.cached_weighted_score %>
      <%= link_to dislike_comment_path(comment), method: :put do %>
        &#x25BC
    <% end %> -
    <a data-toggle="collapse" data-parent="#accordion" href="#<%= comment.id %>">Reply</a>
      <% if current_user == comment.user %> - <%= link_to "Edit", edit_comment_path(comment) %>
        - <%= link_to "Delete", [@commentable, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
  </div>
  <div id="<%= comment.id %>" class="panel-collapse collapse">
  <%= form_for [comment, Comment.new] do |f| %>
      <div class="field">
          <%= f.text_area :body, placeholder: "Add a Reply", class: "form-control" %>
          <%= f.submit "Save", class: "btn btn-sm btn-default" %>
      </div>
  <% end %>
  </div></small>
</div>
<ul>
    <%= render partial: 'comments/comment', collection: comment.comments.order(:cached_votes_score => :desc) %>
    <% end %>
</ul>

app/views/comments/edit.html.erb
<div class="container" id="textblock" >
<h1>Edit comment</h1>
<%= form_for(@comment) do |f| %>
  <div class="field">
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', :back %>
</div>