config/routes.rb
Rails.application.routes.draw do
    root to: 'visitors#index'


    # user routes
    resources  :users do
      resources :campaigns
    end

    get 'users/:id/user_posts' => 'users#user_posts', :as => :custom_user_posts
    # string -- user.email.split("@")[0]


    # session routes
    get '/login' => 'users#login'
    get '/auth/:provider/callback' => 'sessions#create'
    get '/signin' => 'sessions#new', :as => :signin
    get '/signout' => 'sessions#destroy', :as => :signout
    get '/auth/failure' => 'sessions#failure'

    # campaign routes
    get '/c/index' => 'campaigns#index', as: :index_campaign
    get '/c/create' => 'campaigns#campaign_creation', as: :create_campaign
    post '/c/create' => 'campaigns#show'
    get '/c/:id' => 'campaigns#show', as: :show_campaign
    resources :campaigns do
      resources :comments
    end

    resources :comments do
      resources :comments
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end

    resources :comments do 
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end

  end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
	validates_uniqueness_of :title
	validates_uniqueness_of :qr_code
	validates_length_of :qr_code, minimum: 26, maximum: 34
	before_save :website_check

	has_many :comments, as: :commentable
	belongs_to :user
	
	protected
		def website_check
        	u = URI(self.website)
        	if (!u.scheme)
            	self.website = "http://#{self.website}"
        end
    end
end

app/controllers/campaigns_controller.rb
require 'open-uri'

class CampaignsController < ApplicationController
	before_action :authenticate_user!, :only => [:campaign_creation, :create]

	def campaign_creation
		@campaign = Campaign.new
	end

	def create
		@campaign = Campaign.new(campaign_params)
		@campaign.ownership = current_user.id
		@campaign.save

		ws = Webshot::Screenshot.instance
		ws.capture @campaign.website, "app/assets/images/sourceimages/source_#{@campaign.id}.png", width: 800, height: 600, quality: 85
		
		# dealing with cover image
		##upload_path = Rails.root.join("app","assets","images","cover_images")
		##image_name =  params[:campaign][:cover_image].original_filename
		##File.open(upload_path + image_name, 'wb') do |f|
		##	f.write(params[:campaign][:cover_image].read)
		##end
		#this is stupid notation, should be changed, but for some reason adding the strings kept adding an unnecessary "/" and broke the thing
		##File.rename(upload_path.join(image_name), upload_path + "#{Campaign.find_by_title(params[:campaign][:title]).id.to_s}#{File.extname(image_name)}")

		redirect_to "/c/#{@campaign.id}"
	end

	def edit
		@campaign = Campaign.find(params[:id])
	end

	def update
		@campaign = Campaign.find(params[:id])

    	respond_to do |format|
    		if @campaign.update(campaign_params)
      		format.html { redirect_to(@campaign, :action => 'show' , :notice => 'Address was successfully updated.') }
      		format.js
    	end
    end
	end

	def show
		@campaign = Campaign.find(params[:id])
		@campaign.views += 1
		@current_bitcoin_price = JSON.parse(open('https://api.coindesk.com/v1/bpi/currentprice.json').read)['bpi']['USD']['rate'].to_f.round(2)
		@total_deposit = JSON.parse(open("https://blockchain.info/address/#{@campaign.qr_code}?format=json").read)['total_received']
		@account_value = JSON.parse(open("https://blockchain.info/address/#{@campaign.qr_code}?format=json").read)['final_balance']
		@tx_count = JSON.parse(open("https://blockchain.info/address/#{@campaign.qr_code}?format=json").read)['n_tx']
		@total_btc = @total_deposit / 100.to_f.round(10)
		@current_balance = @account_value / 100.to_f.round(10)
		@transaction = JSON.parse(open("https://blockchain.info/address/#{@campaign.qr_code}?format=json&limit=10").read)['txs']
		parent_comments = Comment.where(:commentable_id => @campaign.id)
    	child_comments = Comment.where(:commentable_id => parent_comments.map(&:id))
    	@all_comments = parent_comments + child_comments

    	# potentially could make it unique to each session
		@campaign.save
	end

	def index
		@campaigns = Campaign.all
		
	end

	private
		def campaign_params
			#missing: uploaded_qr_code, tags
			#tags to come when dynamically searching for keywords
			params.require(:campaign).permit(:title,:type,:preferred_currency, :category,:qr_code, :goal, :description, :website)
    	end
    
end

app/helpers/campaigns_helper.rb
module CampaignsHelper

end

app/views/campaigns/_edit.html.erb
<%= form_for(@campaign, remote: true, id: "update_desc") do |f| %>
  <div class="field">
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/campaigns/_form.html.erb
<style>
	#pref-coin{
		font-weight: bold;
	}
	#required{
		color:red;
	}
</style>

<div class = "container" style = "width: 600px; margin-left: 25px; margin-bottom: 50px; float: left;" id = "newproject">
<%= form_for @campaign do |f| %>
	<div class = 'col-md-offset-1' style ='margin-top:5px; align:left;'>
         <div class = "row top-buffer">
           <h1>Add a New Address</h1>
           <br><span id ="pref-coin">Public Address: </span><span id = "required">*</span><br/><%= f.text_field :qr_code, :required => true%>

         </div>
		<div class = "row top-buffer">
            Address Name: <span id = "required">*</span><br/> <%= f.text_field :title, :required => true %><br>
		</div>
        <div class = 'row top-buffer'>
          <div class="wrapper">
            Key Source:
            <div class="tooltip">Where could someone verify the owner or source of this public address?</div>
          </div>
            <%= f.text_field :website, :id => "originSite" %>
          </div>
<!-- 		<div class ="row top-buffer">
			Category: <%= f.select :category, ["Uncategorized", "People", "Events", "Non-profit Organizations", "Websites and Blogs", "Software", "Businesses", "Media and Content Creation", "Authors", "Singers", "Other"]%>
		</div> -->
          <div class = 'row top-buffer'>
            Description: <span id = "required">*</span><br/> <%= f.text_area :description, :required => true, :placeholder => "Tell us about why this account is interesting.", :rows=>'6', :cols=> "55", :style => "" %><br>
          </div>
      <div class = 'row' style = "float: right; padding-top: 10px;">
        <%= f.submit "Add Address", :class => "btn btn-lg btn-primary", :style => 'margin-bottom: 50px; margin-right: 50px;' %>
        </div>
<!--       <div class = 'row' style = "padding-top: 10px;" >
        Optional Cover Image <%= f.file_field :cover_image, :text => "Upload Cover Image", :class => "btn btn-sm btn-alert"%>
      </div> -->
          <!-- javascript here to generate a default suggestion description using title, category, preferred currency-->
          <script>
			//select B and D and L or whatever from unicode
			document.getElementById("campaign_preferred_currency").onchange = function(){
				document.getElementById("pref-coin-initial").innerHTML = this.options[this.selectedIndex].text[0];	
				document.getElementById("pref-coin").innerHTML = this.options[this.selectedIndex].text;
			}
			function changeElement() {
				var elementCheckMark = document.getElementById("campaign_open_donations")
				var outputField = document.getElementById("campaign_goal")
				if (elementCheckMark.checked === true){
					
					outputField.disabled = true
					outputField.value = "Open Donations"
				}	
				else{
					outputField.disabled = false
					outputField.value = ""
				}
			}
			</script>
<% end %>

</div>

app/views/campaigns/_list.html.erb
<style>
	tr.row {
		border-bottom: 1px solid grey;
		margin-top: 50px;

    }
	td#thumbnail{
		margin-top: 50px;
	}

	td#details {
		display:inline;
	}

	td#goal_zone {
		text-align:right;
	}
</style>

<table>
	<tbody>
		<% @campaigns[0..9].sort_by(&locals[:organize].to_sym).each do |c| %>
			<tr class = 'row border_bottom'>
				<td class = "thumbnail" id="listthumb">
					<% if File.exists?("app/assets/images/sourceimages/source_#{c.id}.png") %>
          				<%= image_tag("sourceimages/source_#{c.id}.png") %>
          			<% else %>
        			<% end %>	
				</td>
				<td class = "details">
					<font size=4><%= link_to c.title, show_campaign_path(c.id)%></font><small><br>
					Posted by: <%= link_to User.find(c.ownership).name, user_path(c.ownership) %> - <%= c.comments.size %> comments -
                      <% if c.website.present? %>
                        <%= link_to 'Source Link', c.website, :target => '_blank' %> -
                      <% else %> 
                      	<font color = red><%= 'No Source Provided -' %> </color>
                      <% end %>
                    <a type="button" data-toggle="modal" data-target="#myModal<%= c.qr_code %>">View QR</a>
                    	<div id="myModal<%= c.qr_code %>" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        	<div class="modal-dialog">
                        		<div class="modal-content">
                            		<div class="modal-body">
                            			<div class="modal-info">
                            				<center><h1><%= c.title %></h1>
                            				<%= c.qr_code %></center>
                            			</div>
                              			<img src="http://chart.googleapis.com/chart?cht=qr&chs=500x500&chl=<%= c.qr_code %>" class="img-responsive">
                            		</div>
                          		</div>
                    		</div>
                      </div>
				</small></td>
				<td class = "goal_zone">
				<b>PLACEHOLDER SEARCH CRITERIA
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/campaigns/_tags.html.erb
<style>
	li {
		display:inline;
	}
</style>

<!--
<% for tag in Campaign.find_by_title(params[:title].tags.split(",")) %>
	<li><%= button_to tag, '#' %></li>
<% end %>
-->

app/views/campaigns/campaign_creation.html.erb
<head>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet'  type='text/css'>
  <title>Submit a Campaign</title>
<style>
	.top-buffer{
		margin-top: 20px;

	}
	body{
		font-family: "open sans", sans-serif;
	}
</style>
</head>
<body>
	<%= render 'form'%>
</body>
<!--
<script type="text/javascript" src="grid.js"></script>
<script type="text/javascript" src="version.js"></script>
<script type="text/javascript" src="detector.js"></script>
<script type="text/javascript" src="formatinf.js"></script>
<script type="text/javascript" src="errorlevel.js"></script>
<script type="text/javascript" src="bitmat.js"></script>
<script type="text/javascript" src="datablock.js"></script>
<script type="text/javascript" src="bmparser.js"></script>
<script type="text/javascript" src="datamask.js"></script>
<script type="text/javascript" src="rsdecoder.js"></script>
<script type="text/javascript" src="gf256poly.js"></script>
<script type="text/javascript" src="gf256.js"></script>
<script type="text/javascript" src="decoder.js"></script>
<script type="text/javascript" src="qrcode.js"></script>
<script type="text/javascript" src="findpat.js"></script>
<script type="text/javascript" src="alignpat.js"></script>
<script type="text/javascript" src="databr.js"></script>
-->

app/views/campaigns/edit.html.erb
<div class="container" id="textblock" >
<h1>Edit Address</h1>
<%= form_for(@campaign) do |f| %>
  <div class="field">
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', @campaign %>
</div>

app/views/campaigns/edit.js.erb
$('#edit_desc').hide().after('<%= j render("edit") %>');

app/views/campaigns/index.html.erb
<div class="container" id="textblock">
<h1> Campaigns </h1>
<table>
	<tbody>
		<% @campaigns.each do |c| %>
			<tr class = 'row border_bottom'>
				<% if File.exists?("app/assets/images/sourceimages/source_#{c.id}.png") %>
					<td class = "thumbnail" id="listthumb">
          				<%= image_tag("sourceimages/source_#{c.id}.png") %> </td>
          		<% else %>			
        		<% end %>	
				<td class = "details">
                    <%= link_to c.title, show_campaign_path(c.id)%><br>
                  Posted by: <%= User.find(c.ownership).name %> - <%= c.comments.count %> comments -
                  <% if c.website.present? %>
                      <%= link_to 'Source Link', c.website, :target => '_blank' %> - <% end %><a type="button" data-toggle="modal" data-target="#myModal<%= c.qr_code %>">View QR</a>
                  <div id="myModal<%= c.qr_code %>" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-body">
                          <img src="http://chart.googleapis.com/chart?cht=qr&chs=500x500&chl=<%= c.qr_code %>" class="img-responsive">
                        </div>
                      </div>
                    </div>
                  </div><br>
				</td>
				<!--
				<td class = "goal_zone">
					<%= if c.preferred_currency == "Bitcoin" then pref_currency_inital = "\u0E3F" else pref_currency_inital = "\u00d0;" end%>
					<%= if c.goal.to_i == 0 then "Open Donations" else "Goal: " + c.goal + pref_currency_inital.encode("utf-8") end %>
				</td>
				-->
			</tr>
		<% end %>
	</tbody>
</table>

app/views/campaigns/show.html.erb
<div class="container" id="projectbody">
  <div class="jumbotron" id="campaignjumbo">
    <div><h1><%=@campaign.title%></h1></div>
    <i>views: <%= @campaign.views %></i><br>
    <h3><b><%= @campaign.qr_code %></b></h3>
  </div>
  <div>
    <ul class="nav nav-tabs">
      <li class="active"><a href="#user" data-toggle="tab">Overview</a></li>
      <li><a href="#feedback" data-toggle="tab">Details</a></li>
      <div id="exchangeinfo" align="right">Current Exchange: 1 BTC = $<%= @current_bitcoin_price %>USD</div>
    </ul>
  </div>
  <div class="tab-content">
    <div class="tab-pane active" id="user">
      <div class="col-lg-9 col-md-9">
        <div id="coverimage">
        <% if File.exists?("app/assets/images/sourceimages/source_#{@campaign.id}.png") %>
          <%= image_tag("sourceimages/source_#{@campaign.id}.png") %>
          <% else %>
        <% end %>
          <div id="description"
          <p><%= markdown(@campaign.description) %><small><%= link_to "Edit", edit_campaign_path, remote: true, id: "edit_desc" %></small></p>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3" id="sidebar">
        <img src="http://chart.googleapis.com/chart?cht=qr&chs=200x200&chl=<%= @campaign.qr_code %>">
        <h2><%= number_with_delimiter(@current_balance) %></h2><h5>bits currently held</h5>
        <h3><%= @tx_count %></h3><h5>transactions</h5>
        <h3><%= number_with_delimiter(@total_btc) %></h3><h5>bits received</h5>
        <h3><% if @campaign.website.blank? %>
              <a class="btn btn-danger disabled">No Source Link</a>
          <% else %>
              <a href="http://<%= @campaign.website %>" class="btn btn-success" target="_blank">View Source</a>
          <% end %>
          </h3>
        <a class="btn btn-primary" type="button" data-toggle="modal" data-target="#myModal">View QR Code</a>
        <div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-body">
                <img src="http://chart.googleapis.com/chart?cht=qr&chs=500x500&chl=<%= @campaign.qr_code %>" class="img-responsive">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div><!-- @end #user -->
    <div class="tab-pane" id="feedback">
      <div>
        <br>
        <table class = 'table-striped table-bordered table-condensed table-responsive' style = "table-layout:auto;">
          <thead><th>Donation Info </th><th>Donation Info</th></thead>

          <tr><td class = "auto">Submitted:</td><td> <%= @campaign.created_at %></td></tr>
          <tr><td>Page views:</td><td> <%= @campaign.views%></td></tr>
          <tr><td>Address:</td><td><%=@campaign.qr_code%></td></tr>
          <tr><td>Tags:</td><td><%=@campaign.tags%></td></tr>
          <tr><td>Source:</td><td><%=@campaign.website%></td></tr>
        </table>
      </div>
    </div><!-- @end #feedback -->
  </div><!-- @end .tab-content -->

  <div class="container" id="projectdetails">
    <div class="tab-content col-md-10">
    </div>
  </div><!-- tab content -->
  <div id="donationdetails">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#stream" data-toggle="tab">Discussion</a></li>
      <li><a href="#comments" data-toggle="tab">Donation Stream</a></li>
    </ul>

    <div class="tab-content">
      <div class="tab-pane" id="comments">
        <h3>Recent Transfers To: <i><%=@campaign.title%></i></h3>
        <table class="table" >
        <thead>
          <tr>
            <th>Date</th>
            <th>Comment</th>
            <th>Amount</th>
            <th>Link</th>
          </tr>
        </thead>
        <tbody>
        <% @transaction.each do |t| %>
          <% @tx_change = open('https://blockchain.info/es/q/txresult/'+ t['hash'] + '/'+ @campaign.qr_code + '?api_code=4def58da-fcc3-44d9-abe1-a3e311a76a4f').read %>
            <% if @tx_change.to_i > 0 %>
              <tr style="background-color:#e6ffe6">
            <% else %>
              <tr style="background-color:#ffcccc">
            <% end %>
              <td><%= Time.at(t['time']).strftime("%b %e, %Y @ %l:%M%P") %></td>
              <td><%= t['out'][0]['addr_tag'] %></td>
              <td><%= @tx_change.to_i / 100.to_f.round(10) %> bits</td>
              <td><%= link_to 'More Details' , 'https://blockchain.info/tx/' + t['hash'], :target => '_blank' %></td>
            </tr>
            <% end %>
        </tbody>
      </table>
      </div><!-- @end #stream -->
      <div class="tab-pane active" id="stream">

        <h3 class="comments_title">
         <%= @all_comments.count %> Comments
        </h3>
        <%= form_for [@campaign, Comment.new] do |f| %>
            <%= f.text_area :body, placeholder: "Add a comment", class: "form-control", rows: "3" %>
            <br>
            <%= f.submit "Add Comment", class: "btn btn-sm btn-default" %>
        <% end %>
        <hr>
        <ul>
          <%= render(partial: 'comments/comment', collection: @campaign.comments.order(:cached_votes_score => :desc)) %>
        </ul>
<!-- @end #comments -->
</div><!-- @end .tab-content -->

app/views/campaigns/update.js.erb
$('#description').load(location.href + " #description");
$('.edit_campaign').remove()
$('#edit_desc').show()