config/routes.rb
Rails.application.routes.draw do
    root to: 'visitors#index'


    # user routes
    resources  :users do
      resources :campaigns
    end

    get 'users/:id/user_posts' => 'users#user_posts', :as => :custom_user_posts
    # string -- user.email.split("@")[0]


    # session routes
    get '/login' => 'users#login'
    get '/auth/:provider/callback' => 'sessions#create'
    get '/signin' => 'sessions#new', :as => :signin
    get '/signout' => 'sessions#destroy', :as => :signout
    get '/auth/failure' => 'sessions#failure'

    # campaign routes
    get '/c/index' => 'campaigns#index', as: :index_campaign
    get '/c/create' => 'campaigns#campaign_creation', as: :create_campaign
    post '/c/create' => 'campaigns#show'
    get '/c/:id' => 'campaigns#show', as: :show_campaign
    resources :campaigns do
      resources :comments
    end

    resources :comments do
      resources :comments
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end

    resources :comments do 
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end

  end

app/views/layouts/_account_bar.html.erb
<div class = "navbar navbar-inverse navbar-fixed-top">
	<div class = "containter container-fluid">
	<% if current_user %>
		<li><%= link_to current_user.name, users_show_path, :style => "font-weight: bold;"%></li>
	<% else %>
		<li><%= link_to "Login", login_path %></li>
	<% end %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar" role= "navigation">
  <div class="container container-fluid">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <nav class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-left links" style= "transition:none;">
        <%= render 'layouts/navigation_links' %>
        <!-- want no transition here -->

      </ul>
    </div>
      <ul class="SubmitButton"><%= button_to "Add an Address!", create_campaign_path, :method => :get, :class => "btn btn-md btn-block btn-primary", :style => "margin-top: 18px;"%></ul>

      </div>



</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<li><%= link_to image_tag("logo.gif"), root_url%></li>
<li><%= link_to 'Home', root_url%></li>
<% if user_signed_in? %>
  <li><%= link_to 'Sign out', signout_path %></li>
<% else %>
  <li><%= link_to 'Sign in', login_path %></li>
<% end %>

  <!-- I feel like this link is unnecessary. <li>##<%= link_to 'Campaigns', index_campaign_path %></li> -->

<!--just showing off here... sorry-->
<% for static in Dir.entries(Rails.root.join("app", "views","pages")).map { |file_name| file_name.split(".")[0] }.compact %>
	<li><%= link_to static.capitalize, page_path(static.downcase) %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Little Bit Back" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Littlebitback" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  </head>
  <body>
    <header style= "margin:0px; padding:0px; border:0px">
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" style ="margin:0px; padding:0px; border:0px;">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>

  <div id="footer">
    <div id="footcontent">
        <p>2016 - Little Bit Back - Project Terms and Privacy Policy</p>
    </div>
  </div>
</html>